name: CASAML
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - torch
  - torchvision
  - pytorch-lightning
  - scikit-learn
  - scikit-image 
  - numpy
  - matplotlib
  - napari
  - pandas
  - seaborn
  - pip
  - jupyterlab=3.*
  - ipywidgets
  - fastparquet
  - pyarrow
  - tensorflow
  - tensorflow_addons
  - pip:
    - albumentations
    - captum
    - tqdm
    - opencv-python
    - psutil
    - tensorboard
    - tensorboard-plugin-wit
    - kaggle
    - mediapipe
    - Sphinx
    - jsonargparse[signatures]
    - omegaconf