TransformerSequenceClassifier:
  batch_first: true
  d_model: 192
  dim_feedforward: 1024
  dropout: 0.05
  layer_norm_eps: 1.0e-05
  learning_rate: 0.00106
  n_head: 8
  norm_first: true
  num_classes: 250
common_params:
  learning_rate: 0.001
  n_models: 2
  num_classes: 250
lstm_params:
  dropout: 0.05
  hidden_dim: 512
  input_dim: 192
  layer_dim: 4
