models:
  TransformerPredictor:
    d_model: 192
    n_head: 8
    dim_feedforward: 512
    dropout: 0.3
    layer_norm_eps: !!float 1e-6
    norm_first: True
    batch_first: True
    num_layers: 4
    num_classes: 250
    learning_rate: 0.0001
    gamma: 0.90
    augmentation_threshold: 0.35
    tune:
      n_head:
        min: 4
        max: 8
        mode: choice
      learning_rate:
        min: 0.001
        max: 0.01
        mode: loguniform
      gamma:
        min: 0.9
        max: 0.99
        mode: lognormal
      batch_size:
        min: 64
        max: 1024
        mode: choice


  LSTMPredictor:
    input_dim: 192
    hidden_dim: 100
    layer_dim: 5
    output_dim: 250
    learning_rate: 0.001
    gamma: 0.9
    augmentation_threshold: 0.35
  HybridModel:
    transformer_params:
      d_model: 192
      n_head: 8
      dim_feedforward: 512
      dropout: 0.1
      layer_norm_eps: !!float 1e-5
      norm_first: True
      batch_first: True
      num_layers: 4
    lstm_params:
      input_dim: 192
      hidden_dim: 100
      layer_dim: 4
      dropout: 0.1
    common_params:
      num_classes: 250
      learning_rate: 0.001
  TransformerEnsemble:
    TransformerSequenceClassifier:
      d_model: 192
      n_head: 8
      dim_feedforward: 2048
      dropout: 0.05
      layer_norm_eps: !!float 1e-5
      norm_first: True
      batch_first: True
      num_classes: 250
      learning_rate: 0.0011
    common_params:
      num_classes: 250
      learning_rate: 0.0011
      gamma: 0.9
      n_models: 5
  HybridEnsembleModel:
    TransformerSequenceClassifier:
      d_model: 192
      n_head: 8
      dim_feedforward: 1024
      dropout: 0.05
      layer_norm_eps: !!float 1e-5
      norm_first: True
      batch_first: True
      num_classes: 250
      learning_rate: 0.00106
    lstm_params:
      input_dim: 192
      hidden_dim: 512
      layer_dim: 4
      dropout: 0.05
    common_params:
      num_classes: 250
      learning_rate: 0.001
      n_models: 2
