models:
  TransformerPredictor:
    params:
      d_model: 192
      n_head: 8
      dim_feedforward: 512
      dropout: 0.001
      layer_norm_eps: !!float 1e-6
      norm_first: True
      batch_first: True
      num_layers: 3
      num_classes: 250
      augmentation_threshold: 0.35
    hparams:
      learning_rate: 0.011
      gamma: 0.9

    optimizer:
      name: Adam
    criterion:
      name: CrossEntropyLoss
      logits: True



  LSTMPredictor:
    params:
      input_dim: 192
      hidden_dim: 100
      layer_dim: 5
      output_dim: 250
      dropout: 0.5
    hparams:
      learning_rate: 0.001
      gamma: 0.9
    optimizer:
      name: Adam
    criterion:
        name: CrossEntropyLoss
        logits: True

  HybridModel:
    transformer_params:
      d_model: 192
      n_head: 8
      dim_feedforward: 512
      dropout: 0.001
      layer_norm_eps: !!float 1e-5
      norm_first: True
      batch_first: True
      num_layers: 4
    lstm_params:
      params:
        input_dim: 192
        hidden_dim: 512
        layer_dim: 4
        dropout: 0.001
    common_params:
      num_classes: 250
      learning_rate: 0.001
    optimizer:
      name: Adam
    criterion:
      name: CrossEntropyLoss
      logits: True

  TransformerEnsemble:
    TransformerSequenceClassifier:
      d_model: 192
      n_head: 8
      dim_feedforward: 2048
      dropout: 0.01
      layer_norm_eps: !!float 1e-5
      norm_first: True
      batch_first: True
      num_classes: 250
      learning_rate: 0.0011
    common_params:
      num_classes: 250
      learning_rate: 0.011
      gamma: 0.9
      n_models: 5
    optimizer:
      name: Adam
    criterion:
      name: CrossEntropyLoss
      logits: True

  HybridEnsembleModel:
    TransformerSequenceClassifier:
      d_model: 192
      n_head: 8
      dim_feedforward: 2048
      dropout: 0.01
      layer_norm_eps: !!float 1e-5
      norm_first: True
      batch_first: True
      num_classes: 250
      learning_rate: 0.00106
    lstm_params:
      params:
        input_dim: 192
        hidden_dim: 512
        layer_dim: 4
        dropout: 0.05
    common_params:
      num_classes: 250
      learning_rate: 0.001
      n_models: 4

  CVTransferLearningModel:
    params:
        num_classes: 250
    hparams:
      backbone: resnet152
      weights: null
      learning_rate: 0.001
      gamma: 0.95
    optimizer:
      name: Adam
    criterion:
        name: CrossEntropyLoss
        logits: False


  YetAnotherTransformer:
    YetAnotherTransformerClassifier:
      learning_rate: 0.01
      d_model: 192
      embed_dim: 32
      n_head: 8
      expansion_factor: 4
      drop_rate: 0.0001
      attn_dropout: 0.0001
      num_layers: 2
      num_classes: 250
    common_params:
      num_classes: 250
      learning_rate: 0.001
      gamma: 0.9
    optimizer:
      name: Adam
    criterion:
      name: CrossEntropyLoss
      logits: True

  YetAnotherEnsemble:
    YetAnotherTransformerClassifier:
      learning_rate: 0.01
      d_model: 192
      embed_dim: 64
      n_head: 8
      expansion_factor: 4
      drop_rate: 0.0001
      attn_dropout: 0.001
      num_classes: 250
    common_params:
      num_classes: 250
      learning_rate: 0.001
      gamma: 0.95
      n_models: 6
    optimizer:
      name: Adam
    criterion:
      name: CrossEntropyLoss
      logits: True

