TransformerSequenceClassifier:
  batch_first: true
  d_model: 192
  dim_feedforward: 2048
  dropout: 0.05
  layer_norm_eps: 1.0e-05
  learning_rate: 0.0011
  n_head: 8
  norm_first: true
  num_classes: 250
common_params:
  learning_rate: 0.0011
  n_models: 5
  num_classes: 250
